let perk = 
[
	{
		"id": 1,
		"image_file": "iconPerks_aceInTheHole.png",
		"name_en": "Ace in the Hole",
		"name_ja": "最後の切り札",
		"name_it": "Asso nella Manica",
		"detail_name": "aceInTheHole",
		"side": "surv",
		"belongTo_en": "Ace Visconti",
		"belongTo_it": "Ace Visconti",
		"belongTo_ja": "エース・ヴィスコンティ"
	},
	{
		"id": 2,
		"image_file": "iconPerks_adrenaline.png",
		"name_en": "Adrenaline",
		"name_ja": "アドレナリン",
		"name_it": "Adrenalina",
		"detail_name": "adrenaline",
		"side": "surv",
		"belongTo_en": "Meg Thomas",
		"belongTo_it": "Meg Thomas",
		"belongTo_ja": "メグ・トーマス"
	},
	{
		"id": 3,
		"image_file": "iconPerks_aftercare.png",
		"name_en": "Aftercare",
		"name_ja": "アフターケア",
		"name_it": "Convalescenza",
		"detail_name": "aftercare",
		"side": "surv",
		"belongTo_en": "Jeffrey \"Jeff\" Johansen",
		"belongTo_it": "Jeffrey \"Jeff\" Johansen",
		"belongTo_ja": "ジェフ・ヨハンセン"
	},
	{
		"id": 4,
		"image_file": "iconPerks_agitation.png",
		"name_en": "Agitation",
		"name_ja": "興奮",
		"name_it": "Agitazione",
		"detail_name": "agitation",
		"side": "killer",
		"belongTo_en": "Trapper",
		"belongTo_it": "Cacciatore",
		"belongTo_ja": "トラッパー"
	},
	{
		"id": 5,
		"image_file": "iconPerks_alert.png",
		"name_en": "Alert",
		"name_ja": "警戒",
		"name_it": "Allerta",
		"detail_name": "alert",
		"side": "surv",
		"belongTo_en": "Feng Min",
		"belongTo_it": "Feng Min",
		"belongTo_ja": "フェン・ミン"
	},
	{
		"id": 6,
		"image_file": "iconPerks_aNursesCalling.png",
		"name_en": "A Nurse's Calling",
		"name_ja": "看護婦の使命",
		"name_it": "Vocazione di un'Infermiera",
		"detail_name": "aNursesCalling",
		"side": "killer",
		"belongTo_en": "Nurse",
		"belongTo_it": "Infermiera",
		"belongTo_ja": "ナース"
	},
	{
		"id": 7,
		"image_file": "iconPerks_anyMeansNecessary.png",
		"name_en": "Any Means Necessary",
		"name_ja": "強硬手段",
		"name_it": "A Ogni Costo",
		"detail_name": "anyMeansNecessary",
		"side": "surv",
		"belongTo_en": "Yui Kimura",
		"belongTo_it": "Yui Kimura",
		"belongTo_ja": "木村 結衣"
	},
	{
		"id": 8,
		"image_file": "iconPerks_appraisal.png",
		"name_en": "Appraisal",
		"name_ja": "査定",
		"name_it": "Stima",
		"detail_name": "appraisal",
		"side": "surv",
		"belongTo_en": "Élodie Rakoto",
		"belongTo_it": "Élodie Rakoto",
		"belongTo_ja": "エロディー・ラコト"
	},
	{
		"id": 9,
		"image_file": "iconPerks_autodidact.png",
		"name_en": "Autodidact",
		"name_ja": "独学者",
		"name_it": "Autoapprendimento",
		"detail_name": "autodidact",
		"side": "surv",
		"belongTo_en": "Adam Francis",
		"belongTo_it": "Adam Francis",
		"belongTo_ja": "アダム・フランシス"
	},
	{
		"id": 10,
		"image_file": "iconPerks_AwakenedAwarenesss.png",
		"name_en": "Awakened Awareness",
		"name_ja": "知覚覚醒",
		"name_it": "Percezione Risvegliata",
		"detail_name": "awakenedAwarenesss",
		"side": "killer",
		"belongTo_en": "Mastermind",
		"belongTo_it": "Mastermind",
		"belongTo_ja": "マスターマインド"
	},
	{
		"id": 12,
		"image_file": "iconPerks_balancedLanding.png",
		"name_en": "Balanced Landing",
		"name_ja": "スマートな着地",
		"name_it": "Atterraggio Bilanciato",
		"detail_name": "balancedLanding",
		"side": "surv",
		"belongTo_en": "Nea Karlsson",
		"belongTo_it": "Nea Karlsson",
		"belongTo_ja": "ネア・カールソン"
	},
	{
		"id": 13,
		"image_file": "iconPerks_bamboozle.png",
		"name_en": "Bamboozle",
		"name_ja": "まやかし",
		"name_it": "Inganno",
		"detail_name": "bamboozle",
		"side": "killer",
		"belongTo_en": "Clown",
		"belongTo_it": "Clown",
		"belongTo_ja": "クラウン"
	},
	{
		"id": 14,
		"image_file": "iconPerks_BBQAndChili.png",
		"name_en": "Barbecue & Chilli",
		"name_ja": "バーベキュー＆チリ",
		"name_it": "Barbecue & Chili",
		"detail_name": "bbqAndChili",
		"side": "killer",
		"belongTo_en": "Cannibal",
		"belongTo_it": "Cannibale",
		"belongTo_ja": "カニバル"
	},
	{
		"id": 15,
		"image_file": "iconPerks_BeastOfPrey.png",
		"name_en": "Beast of Prey",
		"name_ja": "猛獣",
		"name_it": "Animale da Preda",
		"detail_name": "beastOfPrey",
		"side": "killer",
		"belongTo_en": "Huntress",
		"belongTo_it": "Cacciatrice",
		"belongTo_ja": "ハントレス"
	},
	{
		"id": 16,
		"image_file": "iconPerks_BetterThanNew.png",
		"name_en": "Better than New",
		"name_ja": "みなぎる活力",
		"name_it": "Rigenerazione Totale",
		"detail_name": "BetterThanNew",
		"side": "surv",
		"belongTo_en": "Rebecca Chambers",
		"belongTo_it": "Rebecca Chambers",
		"belongTo_ja": "レベッカ・チェンバース"
	},
	{
		"id": 18,
		"image_file": "iconPerks_BiteTheBullet.png",
		"name_en": "Bite the Bullet",
		"name_ja": "忍苦の時",
		"name_it": "Stringi i Denti",
		"detail_name": "biteTheBullet",
		"side": "surv",
		"belongTo_en": "Leon Scott Kennedy",
		"belongTo_it": "Leon Scott Kennedy",
		"belongTo_ja": "レオン・S・ケネディ"
	},
	{
		"id": 19,
		"image_file": "iconPerks_bitterMurmur.png",
		"name_en": "Bitter Murmur",
		"name_ja": "憎悪の囁き",
		"name_it": "Sussurro Amaro",
		"detail_name": "bitterMurmur",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 20,
		"image_file": "iconPerks_blastMine.png",
		"name_en": "Blast Mine",
		"name_ja": "地雷爆破",
		"name_it": "Mina Esplosiva",
		"detail_name": "blastMine",
		"side": "surv",
		"belongTo_it": "Jill Valentine",
		"belongTo_en": "Jill Valentine",
		"belongTo_ja": "ジル・バレンタイン"
	},
	{
		"id": 21,
		"image_file": "iconPerks_bloodEcho.png",
		"name_en": "Blood Echo",
		"name_ja": "血の共鳴",
		"name_it": "Eco Sanguigna",
		"detail_name": "bloodEcho",
		"side": "killer",
		"belongTo_en": "Oni",
		"belongTo_it": "Oni",
		"belongTo_ja": "鬼"
	},
	{
		"id": 22,
		"image_file": "iconPerks_bloodhound.png",
		"name_en": "Bloodhound",
		"name_ja": "血の追跡者",
		"name_it": "Segugio",
		"detail_name": "bloodhound",
		"side": "killer",
		"belongTo_en": "Wraith",
		"belongTo_it": "Spettro",
		"belongTo_ja": "レイス"
	},
	{
		"id": 23,
		"image_file": "iconPerks_bloodPact.png",
		"name_en": "Blood Pact",
		"name_ja": "血の協定",
		"name_it": "Patto di Sangue",
		"detail_name": "bloodPact",
		"side": "surv",
		"belongTo_en": "Cheryl Mason",
		"belongTo_it": "Cheryl Mason",
		"belongTo_ja": "シェリル・メイソン"
	},
	{
		"id": 24,
		"image_file": "iconPerks_bloodWarden.png",
		"name_en": "Blood Warden",
		"name_ja": "血の番人",
		"name_it": "Custode Sanguinario",
		"detail_name": "bloodWarden",
		"side": "killer",
		"belongTo_en": "Nightmare",
		"belongTo_it": "Incubo",
		"belongTo_ja": "ナイトメア"
	},
	{
		"id": 25,
		"image_file": "iconPerks_boilOver.png",
		"name_en": "Boil Over",
		"name_ja": "ボイルオーバー",
		"name_it": "Perdi le Staffe",
		"detail_name": "boilOver",
		"side": "surv",
		"belongTo_en": "Kate Denson",
		"belongTo_it": "Kate Denson",
		"belongTo_ja": "ケイト・デンソン"
	},
	{
		"id": 26,
		"image_file": "iconPerks_bond.png",
		"name_en": "Bond",
		"name_ja": "絆",
		"name_it": "Legame",
		"detail_name": "bond",
		"side": "surv",
		"belongTo_en": "Dwight Fairfield",
		"belongTo_it": "Dwight Fairfield",
		"belongTo_ja": "ドワイト・フェアフィールド"
	},
	{
		"id": 27,
		"image_file": "iconPerks_BoonCircleOfHealing.png",
		"name_en": "Boon: Circle of Healing",
		"name_ja": "恵み：癒しの輪",
		"name_it": "Manna: Cerchio della Cura",
		"detail_name": "boonCircleOfHealing",
		"side": "surv",
		"belongTo_en": "Mikaela Reid",
		"belongTo_it": "Mikaela Reid",
		"belongTo_ja": "ミカエラ・リード"
	},
	{
		"id": 28,
		"image_file": "iconPerks_BoonDestroyer.png",
		"name_en": "Shattered Hope",
		"name_ja": "打ち砕かれた希望",
		"name_it": "Speranza Affranta",
		"detail_name": "shatteredHope",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 29,
		"image_file": "iconPerks_BoonShadowStep.png",
		"name_en": "Boon: Shadow Step",
		"name_ja": "恵み：シャドウステップ",
		"name_it": "Manna: Passo nell'Ombra",
		"detail_name": "boonShadowStep",
		"side": "surv",
		"belongTo_en": "Mikaela Reid",
		"belongTo_it": "Mikaela Reid",
		"belongTo_ja": "ミカエラ・リード"
	},
	{
		"id": 30,
		"image_file": "iconPerks_borrowedTime.png",
		"name_en": "Borrowed Time",
		"name_ja": "与えられた猶予",
		"name_it": "Tempo Prezioso",
		"detail_name": "borrowedTime",
		"side": "surv",
		"belongTo_en": "William \"Bill\" Overbeck ",
		"belongTo_it": "William \"Bill\" Overbeck ",
		"belongTo_ja": "ウィリアム・ビル・オーバーバック"
	},
	{
		"id": 31,
		"image_file": "iconPerks_botanyKnowledge.png",
		"name_en": "Botany Knowledge",
		"name_ja": "植物学の知識",
		"name_it": "Conoscenze Botaniche",
		"detail_name": "botanyKnowledge",
		"side": "surv",
		"belongTo_en": "Claudette Morel",
		"belongTo_it": "Claudette Morel",
		"belongTo_ja": "クローデット・モレル"
	},
	{
		"id": 32,
		"image_file": "iconPerks_breakdown.png",
		"name_en": "Breakdown",
		"name_ja": "ブレイクダウン",
		"name_it": "Collasso",
		"detail_name": "breakdown",
		"side": "surv",
		"belongTo_en": "Jeffrey \"Jeff\" Johansen",
		"belongTo_it": "Jeffrey \"Jeff\" Johansen",
		"belongTo_ja": "ジェフ・ヨハンセン"
	},
	{
		"id": 33,
		"image_file": "iconPerks_breakout.png",
		"name_en": "Breakout",
		"name_ja": "突破",
		"name_it": "Evasione",
		"detail_name": "breakout",
		"side": "surv",
		"belongTo_en": "Yui Kimura",
		"belongTo_it": "Yui Kimura",
		"belongTo_ja": "木村 結衣"
	},
	{
		"id": 34,
		"image_file": "iconPerks_brutalStrength.png",
		"name_en": "Brutal Strength",
		"name_ja": "野蛮な力",
		"name_it": "Forza Brutale",
		"detail_name": "brutalStrength",
		"side": "killer",
		"belongTo_en": "Trapper",
		"belongTo_it": "Cacciatore",
		"belongTo_ja": "トラッパー"
	},
	{
		"id": 35,
		"image_file": "iconPerks_buckleUp.png",
		"name_en": "Buckle Up",
		"name_ja": "ベルトを締めろ！",
		"name_it": "Allaccia le Cinture",
		"detail_name": "buckleUp",
		"side": "surv",
		"belongTo_en": "Ashley J. Williams",
		"belongTo_it": "Ashley J. Williams",
		"belongTo_ja": "アシュレイ・J・ウィリアムズ"
	},
	{
		"id": 36,
		"image_file": "iconPerks_builtToLast.png",
		"name_en": "Built to Last",
		"name_ja": "耐久設計",
		"name_it": "Costruito per Durare",
		"detail_name": "builtToLast",
		"side": "surv",
		"belongTo_en": "Felix Richter",
		"belongTo_it": "Felix Richter",
		"belongTo_ja": "フェリックス・リクター"
	},
	{
		"id": 37,
		"image_file": "iconPerks_callOfBrine.png",
		"name_en": "Call of Brine",
		"name_ja": "海の呼び声",
		"name_it": "Richiamo Salmastro",
		"detail_name": "callOfBrine",
		"side": "killer",
		"belongTo_en": "Onryō",
		"belongTo_it": "Onryō",
		"belongTo_ja": "怨霊"
	},
	{
		"id": 38,
		"image_file": "iconPerks_calmSpirit.png",
		"name_en": "Calm Spirit",
		"name_ja": "魂の平穏",
		"name_it": "Spirito Calmo",
		"detail_name": "calmSpirit",
		"side": "surv",
		"belongTo_en": "Jake Park",
		"belongTo_it": "Jake Park",
		"belongTo_ja": "ジェイク・パーク"
	},
	{
		"id": 39,
		"image_file": "iconPerks_camaraderie.png",
		"name_en": "Kinship",
		"name_ja": "仲間意識",
		"name_it": "Affinità",
		"detail_name": "kinship",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 40,
		"image_file": "iconPerks_Clairvoyance.png",
		"name_en": "Clairvoyance",
		"name_ja": "千里眼",
		"name_it": "Chiaroveggenza",
		"detail_name": "clairvoyance",
		"side": "surv",
		"belongTo_en": "Mikaela Reid",
		"belongTo_it": "Mikaela Reid",
		"belongTo_ja": "ミカエラ・リード"
	},
	{
		"id": 41,
		"image_file": "iconPerks_corruptIntervention.png",
		"name_en": "Corrupt Intervention",
		"name_ja": "堕落の介入",
		"name_it": "Intervento Corrotto",
		"detail_name": "corruptIntervention",
		"side": "killer",
		"belongTo_en": "Plague",
		"belongTo_it": "Malattia",
		"belongTo_ja": "プレイグ"
	},
	{
		"id": 42,
		"image_file": "iconPerks_coulrophobia.png",
		"name_en": "Coulrophobia",
		"name_ja": "ピエロ恐怖症",
		"name_it": "Coulrofobia",
		"detail_name": "coulrophobia",
		"side": "killer",
		"belongTo_en": "Clown",
		"belongTo_it": "Clown",
		"belongTo_ja": "クラウン"
	},
	{
		"id": 43,
		"image_file": "iconPerks_Counterforce.png",
		"name_en": "Counterforce",
		"name_ja": "カウンターフォース",
		"name_it": "Controforza",
		"detail_name": "counterforce",
		"side": "surv",
		"belongTo_it": "Jill Valentine",
		"belongTo_en": "Jill Valentine",
		"belongTo_ja": "ジル・バレンタイン"
	},
	{
		"id": 44,
		"image_file": "iconPerks_coupDeGrace.png",
		"name_en": "Coup de Grâce",
		"name_ja": "とどめの一撃",
		"name_it": "Colpo di Grazia",
		"detail_name": "coupDeGrace",
		"side": "killer",
		"belongTo_en": "Twins",
		"belongTo_it": "Gemelli",
		"belongTo_ja": "ツインズ"
	},
	{
		"id": 45,
		"image_file": "iconPerks_cruelConfinement.png",
		"name_en": "Claustrophobia",
		"name_ja": "閉所恐怖症",
		"name_it": "Claustrofobia",
		"detail_name": "claustrophobia",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 46,
		"image_file": "iconPerks_danceWithMe.png",
		"name_en": "Dance With Me",
		"name_ja": "ダンス・ウィズ・ミー",
		"name_it": "Balla con Me",
		"detail_name": "danceWithMe",
		"side": "surv",
		"belongTo_en": "Kate Denson",
		"belongTo_it": "Kate Denson",
		"belongTo_ja": "ケイト・デンソン"
	},
	{
		"id": 47,
		"image_file": "iconPerks_darkDevotion.png",
		"name_en": "Dark Devotion",
		"name_ja": "闇の信仰心",
		"name_it": "Devozione Oscura",
		"detail_name": "darkDevotion",
		"side": "killer",
		"belongTo_en": "Plague",
		"belongTo_it": "Malattia",
		"belongTo_ja": "プレイグ"
	},
	{
		"id": 48,
		"image_file": "iconPerks_DarknessRevelated.png",
		"name_en": "Darkness Revealed",
		"name_ja": "露見する闇",
		"name_it": "Oscurità Rivelata",
		"detail_name": "darknessRevelated",
		"side": "killer",
		"belongTo_en": "Dredge",
		"belongTo_it": "Draga",
		"belongTo_ja": "ドレッジ"
	},
	{
		"id": 49,
		"image_file": "iconPerks_darkSense.png",
		"name_en": "Dark Sense",
		"name_ja": "闇の感覚",
		"name_it": "Sensazione Tenebrosa",
		"detail_name": "darkSense",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 50,
		"image_file": "iconPerks_darkTheory.png",
		"name_en": "Boon: Dark Theory",
		"name_ja": "恵み：霊界理論",
		"name_it": "Manna: Teoria Oscura",
		"detail_name": "darkTheory",
		"side": "surv",
		"belongTo_en": "Yoichi Asakawa",
		"belongTo_it": "Yoichi Asakawa",
		"belongTo_ja": "浅川陽一"
	},
	{
		"id": 51,
		"image_file": "iconPerks_DeadHard.png",
		"name_en": "Dead Hard",
		"name_ja": "デッド・ハード",
		"name_it": "Morto Stecchito",
		"detail_name": "deadHard",
		"side": "surv",
		"belongTo_en": "David King",
		"belongTo_it": "David King",
		"belongTo_ja": "デイビット・キング"
	},
	{
		"id": 52,
		"image_file": "iconPerks_Deadlock.png",
		"name_en": "Deadlock",
		"name_ja": "デッドロック",
		"name_it": "Impasse",
		"detail_name": "deadlock",
		"side": "killer",
		"belongTo_en": "Cenobite",
		"belongTo_it": "Cenobita",
		"belongTo_ja": "セノバイト"
	},
	{
		"id": 53,
		"image_file": "iconPerks_deadManSwitch.png",
		"name_en": "Dead Man's Switch",
		"name_ja": "死人のスイッチ",
		"name_it": "Dispositivo dell'Uomo Morto",
		"detail_name": "deadManSwitch",
		"side": "killer",
		"belongTo_en": "Deathslinger",
		"belongTo_it": "Araldo di Morte",
		"belongTo_ja": "デススリンガー"
	},
	{
		"id": 54,
		"image_file": "iconPerks_deathbound.png",
		"name_en": "Deathbound",
		"name_ja": "デスバウンド",
		"name_it": "Morte Certa",
		"detail_name": "",
		"side": "killer",
		"belongTo_en": "Executioner",
		"belongTo_it": "Boia",
		"belongTo_ja": "エクセキューショナー"
	},
	{
		"id": 55,
		"image_file": "iconPerks_deception.png",
		"name_en": "Deception",
		"name_ja": "欺き",
		"name_it": "Raggiro",
		"detail_name": "deception",
		"side": "surv",
		"belongTo_en": "Élodie Rakoto",
		"belongTo_it": "Élodie Rakoto",
		"belongTo_ja": "エロディー・ラコト"
	},
	{
		"id": 56,
		"image_file": "iconPerks_decisiveStrike.png",
		"name_en": "Decisive Strike",
		"name_ja": "決死の一撃",
		"name_it": "Colpo Decisivo",
		"detail_name": "decisiveStrike",
		"side": "surv",
		"belongTo_en": "Laurie Strode",
		"belongTo_it": "Laurie Strode",
		"belongTo_ja": "ローリー・ストロード"
	},
	{
		"id": 57,
		"image_file": "iconPerks_deerstalker.png",
		"name_en": "Deerstalker",
		"name_ja": "忍び寄る者",
		"name_it": "Cacciatore di Cervi",
		"detail_name": "deerstalker",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 58,
		"image_file": "iconPerks_dejaVu.png",
		"name_en": "Déjà Vu",
		"name_ja": "デジャヴ",
		"name_it": "Déjà Vu",
		"detail_name": "dejaVu",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 59,
		"image_file": "iconPerks_deliverance.png",
		"name_en": "Deliverance",
		"name_ja": "解放",
		"name_it": "Liberazione",
		"detail_name": "deliverance",
		"side": "surv",
		"belongTo_en": "Adam Francis",
		"belongTo_it": "Adam Francis",
		"belongTo_ja": "アダム・フランシス"
	},
	{
		"id": 60,
		"image_file": "iconPerks_desperateMeasures.png",
		"name_en": "Desperate Measures",
		"name_ja": "苦肉の策",
		"name_it": "Estremi Rimedi",
		"detail_name": "desperateMeasures",
		"side": "surv",
		"belongTo_en": "Felix Richter",
		"belongTo_it": "Felix Richter",
		"belongTo_ja": "フェリックス・リクター"
	},
	{
		"id": 61,
		"image_file": "iconPerks_detectivesHunch.png",
		"name_en": "Detective's Hunch",
		"name_ja": "刑事の直感",
		"name_it": "Intuizione del Detective",
		"detail_name": "detectivesHunch",
		"side": "surv",
		"belongTo_en": "Detective David Tapp",
		"belongTo_it": "Detective David Tapp",
		"belongTo_ja": "タップ刑事"
	},
	{
		"id": 62,
		"image_file": "iconPerks_devourHope.png",
		"name_en": "Hex: Devour Hope",
		"name_ja": "破滅",
		"name_it": "Maledizione: Divora Speranza",
		"detail_name": "devourHope",
		"side": "killer",
		"belongTo_en": "Hag",
		"belongTo_it": "Strega",
		"belongTo_ja": "ハグ"
	},
	{
		"id": 63,
		"image_file": "iconPerks_discordance.png",
		"name_en": "Discordance",
		"name_ja": "不協和音",
		"name_it": "Discordia",
		"detail_name": "discordance",
		"side": "killer",
		"belongTo_en": "Legion",
		"belongTo_it": "Legione",
		"belongTo_ja": "リージョン"
	},
	{
		"id": 64,
		"image_file": "iconPerks_Dissolution.png",
		"name_en": "Dissolution",
		"name_ja": "解体",
		"name_it": "Dissoluzione",
		"detail_name": "dissolution",
		"side": "killer",
		"belongTo_en": "Dredge",
		"belongTo_it": "Draga",
		"belongTo_ja": "ドレッジ"
	},
	{
		"id": 65,
		"image_file": "iconPerks_distortion.png",
		"name_en": "Distortion",
		"name_ja": "ディストーション",
		"name_it": "Stravolgimento",
		"detail_name": "distortion",
		"side": "surv",
		"belongTo_en": "Jeffrey \"Jeff\" Johansen",
		"belongTo_it": "Jeffrey \"Jeff\" Johansen",
		"belongTo_ja": "ジェフ・ヨハンセン"
	},
	{
		"id": 66,
		"image_file": "iconPerks_distressing.png",
		"name_en": "Distressing",
		"name_ja": "苦悶の根源",
		"name_it": "Inquietante",
		"detail_name": "distressing",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 67,
		"image_file": "iconPerks_diversion.png",
		"name_en": "Diversion",
		"name_ja": "陽動",
		"name_it": "Diversivo",
		"detail_name": "diversion",
		"side": "surv",
		"belongTo_en": "Adam Francis",
		"belongTo_it": "Adam Francis",
		"belongTo_ja": "アダム・フランシス"
	},
	{
		"id": 68,
		"image_file": "iconPerks_dragonsGrip.png",
		"name_en": "Dragon's Grip",
		"name_ja": "ドラゴンの掌握",
		"name_it": "Morsa del Drago",
		"detail_name": "",
		"side": "killer",
		"belongTo_en": "Blight",
		"belongTo_it": "Piaga",
		"belongTo_ja": "ブライト"
	},
	{
		"id": 69,
		"image_file": "iconPerks_dyingLight.png",
		"name_en": "Dying Light",
		"name_ja": "消えゆく灯",
		"name_it": "Luce Morente",
		"detail_name": "dyingLight",
		"side": "killer",
		"belongTo_en": "Shape",
		"belongTo_it": "Ombra",
		"belongTo_ja": "シェイプ"
	},
	{
		"id": 70,
		"image_file": "iconPerks_empathicConnection.png",
		"name_en": "Empathic Connection",
		"name_ja": "共感的つながり",
		"name_it": "Connessione Empatica",
		"detail_name": "empathicConnection",
		"side": "surv",
		"belongTo_en": "Yoichi Asakawa",
		"belongTo_it": "Yoichi Asakawa",
		"belongTo_ja": "浅川陽一"
	},
	{
		"id": 71,
		"image_file": "iconPerks_empathy.png",
		"name_en": "Empathy",
		"name_ja": "共感",
		"name_it": "Conoscenze Botaniche",
		"detail_name": "empathy",
		"side": "surv",
		"belongTo_en": "Claudette Morel",
		"belongTo_it": "Claudette Morel",
		"belongTo_ja": "クローデット・モレル"
	},
	{
		"id": 72,
		"image_file": "iconPerks_enduring.png",
		"name_en": "Enduring",
		"name_ja": "不屈",
		"name_it": "Resistente",
		"detail_name": "enduring",
		"side": "killer",
		"belongTo_en": "Hillbilly",
		"belongTo_it": "Mandriano",
		"belongTo_ja": "ヒルビリー"
	},
	{
		"id": 73,
		"image_file": "iconPerks_eruption.png",
		"name_en": "Eruption",
		"name_ja": "イラプション",
		"name_it": "Eruzione",
		"detail_name": "eruption",
		"side": "killer",
		"belongTo_en": "Nemesis",
		"belongTo_it": "Nemesis",
		"belongTo_ja": "ネメシス"
	},
	{
		"id": 74,
		"image_file": "iconPerks_FastTrack.png",
		"name_en": "Fast Track",
		"name_ja": "出世街道",
		"name_it": "Impazienza",
		"detail_name": "fastTrack",
		"side": "surv",
		"belongTo_en": "Yun-Jin Lee",
		"belongTo_it": "Yun-Jin Lee",
		"belongTo_ja": "リー・ユンジン"
	},
	{
		"id": 75,
		"image_file": "iconPerks_fireUp.png",
		"name_en": "Fire Up",
		"name_ja": "ファイヤー・アップ",
		"name_it": "Fuoco e Fiamme",
		"detail_name": "fireUp",
		"side": "killer",
		"belongTo_en": "Nightmare",
		"belongTo_it": "Incubo",
		"belongTo_ja": "ナイトメア"
	},
	{
		"id": 76,
		"image_file": "iconPerks_fixated.png",
		"name_en": "Self-Aware",
		"name_ja": "自己認識",
		"name_it": "Consapevolezza",
		"detail_name": "selfAware",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 77,
		"image_file": "iconPerks_Flashbang.png",
		"name_en": "Flashbang",
		"name_ja": "スタングレネード",
		"name_it": "Granata Stordente",
		"detail_name": "flashbang",
		"side": "surv",
		"belongTo_en": "Leon Scott Kennedy",
		"belongTo_it": "Leon Scott Kennedy",
		"belongTo_ja": "レオン・S・ケネディ"
	},
	{
		"id": 78,
		"image_file": "iconPerks_flipFlop.png",
		"name_en": "Flip-Flop",
		"name_ja": "フリップ・フロップ",
		"name_it": "Ritorno",
		"detail_name": "flipFlop",
		"side": "surv",
		"belongTo_en": "Ashley J. Williams",
		"belongTo_it": "Ashley J. Williams",
		"belongTo_ja": "アシュレイ・J・ウィリアムズ"
	},
	{
		"id": 79,
		"image_file": "iconPerks_floodOfRage.png",
		"name_en": "Scourge Hook: Floods of Rage",
		"name_ja": "悶絶：氾濫する憤怒",
		"name_it": "Flagello Appuntito: Ira Implacabile",
		"detail_name": "floodOfRage",
		"side": "killer",
		"belongTo_en": "Onryō",
		"belongTo_it": "Onryō",
		"belongTo_ja": "怨霊"
	},
	{
		"id": 80,
		"image_file": "iconPerks_forcedPenance.png",
		"name_en": "ForcedPenance",
		"name_ja": "強制苦行",
		"name_it": "Penitenza Imposta",
		"detail_name": "forcedPenance",
		"side": "killer",
		"belongTo_en": "Executioner",
		"belongTo_it": "Boia",
		"belongTo_ja": "エクセキューショナー"
	},
	{
		"id": 81,
		"image_file": "iconPerks_forThePeople.png",
		"name_en": "For the People",
		"name_ja": "人々のために",
		"name_it": "Per il Popolo",
		"detail_name": "forThePeople",
		"side": "surv",
		"belongTo_en": "Zarina Kassir",
		"belongTo_it": "Zarina Kassir",
		"belongTo_ja": "ザリーナ・カッシル"
	},
	{
		"id": 82,
		"image_file": "iconPerks_franklinsLoss.png",
		"name_en": "Franklin's Demise",
		"name_ja": "フランクリンの悲劇",
		"name_it": "Caduta di Franklin",
		"detail_name": "franklinsLoss",
		"side": "killer",
		"belongTo_en": "Cannibal",
		"belongTo_it": "Cannibale",
		"belongTo_ja": "カニバル"
	},
	{
		"id": 83,
		"image_file": "iconPerks_furtiveChase.png",
		"name_en": "Furtive Chase",
		"name_ja": "隠密の追跡",
		"name_it": "Inseguimento Furtivo",
		"detail_name": "furtiveChase",
		"side": "killer",
		"belongTo_en": "Ghost Face",
		"belongTo_it": "Ghost Face",
		"belongTo_ja": "ゴーストフェイス"
	},
	{
		"id": 84,
		"image_file": "iconPerks_gearHead.png",
		"name_en": "Gearhead",
		"name_ja": "変速機",
		"name_it": "Meccanico",
		"detail_name": "gearHead",
		"side": "killer",
		"belongTo_en": "Deathslinger",
		"belongTo_it": "Araldo di Morte",
		"belongTo_ja": "デススリンガー"
	},
	{
		"id": 85,
		"image_file": "iconPerks_generatorOvercharge.png",
		"name_en": "Overcharge",
		"name_ja": "オーバーチャージ",
		"name_it": "Sovraccarico",
		"detail_name": "overcharge",
		"side": "killer",
		"belongTo_en": "Doctor",
		"belongTo_it": "Dottore",
		"belongTo_ja": "ドクター"
	},
	{
		"id": 86,
		"image_file": "iconPerks_guardian.png",
		"name_en": "Guardian",
		"name_ja": "監視者",
		"name_it": "Guardiano",
		"detail_name": "guardian",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 87,
		"image_file": "iconPerks_hangmansTrick.png",
		"name_en": "Hangman's Trick",
		"name_ja": "処刑人の妙技",
		"name_it": "Gioco dell'Impiccato",
		"detail_name": "hangmansTrick",
		"side": "killer",
		"belongTo_en": "Pig",
		"belongTo_it": "Maiale",
		"belongTo_ja": "ピッグ"
	},
	{
		"id": 88,
		"image_file": "iconPerks_hatred.png",
		"name_en": "Rancor",
		"name_ja": "怨恨",
		"name_it": "Rancore",
		"detail_name": "hatred",
		"side": "killer",
		"belongTo_en": "Spirit",
		"belongTo_it": "Spirito",
		"belongTo_ja": "スピリット"
	},
	{
		"id": 89,
		"image_file": "iconPerks_hauntedGround.png",
		"name_en": "Hex: Haunted Ground",
		"name_ja": "霊障の地",
		"name_it": "Maledizione: Terra Maledetta",
		"detail_name": "hauntedGround",
		"side": "killer",
		"belongTo_en": "Spirit",
		"belongTo_it": "Spirito",
		"belongTo_ja": "スピリット"
	},
	{
		"id": 90,
		"image_file": "iconPerks_headOn.png",
		"name_en": "Head On",
		"name_ja": "真っ向勝負",
		"name_it": "Frontale",
		"detail_name": "headOn",
		"side": "surv",
		"belongTo_en": "Jane Romero",
		"belongTo_it": "Jane Romero",
		"belongTo_ja": "ジェーン・ロメロ"
	},
	{
		"id": 91,
		"image_file": "iconPerks_hexBloodFavor.png",
		"name_en": "Hex: Blood Favour",
		"name_ja": "血の恩恵",
		"name_it": "Maledizione: Favore di Sangue",
		"detail_name": "hexBloodFavor",
		"side": "killer",
		"belongTo_en": "Blight",
		"belongTo_it": "Piaga",
		"belongTo_ja": "ブライト"
	},
	{
		"id": 92,
		"image_file": "iconPerks_HexCrowdControl.png",
		"name_en": "Hex: Crowd Control",
		"name_ja": "クラウドコントロール",
		"name_it": "Maledizione: Controllo delle Folle",
		"detail_name": "hexCrowdControl",
		"side": "killer",
		"belongTo_en": "Trickster",
		"belongTo_it": "Ingannatore",
		"belongTo_ja": "トリックスター"
	},
	{
		"id": 93,
		"image_file": "iconPerks_HexPlaything.png",
		"name_en": "Hex: Plaything",
		"name_ja": "玩具",
		"name_it": "Maledizione: Giocattolo",
		"detail_name": "hexPlaything",
		"side": "killer",
		"belongTo_en": "Cenobite",
		"belongTo_it": "Cenobita",
		"belongTo_ja": "セノバイト"
	},
	{
		"id": 94,
		"image_file": "iconPerks_hexRetribution.png",
		"name_en": "Hex: Retribution",
		"name_ja": "報復",
		"name_it": "Maledizione: Castigo",
		"detail_name": "hexRetribution",
		"side": "killer",
		"belongTo_en": "Deathslinger",
		"belongTo_it": "Araldo di Morte",
		"belongTo_ja": "デススリンガー"
	},
	{
		"id": 95,
		"image_file": "iconPerks_hexUndying.png",
		"name_en": "Hex: Undying",
		"name_ja": "不死",
		"name_it": "Maledizione: Immortale",
		"detail_name": "hexUndying",
		"side": "killer",
		"belongTo_en": "Blight",
		"belongTo_it": "Piaga",
		"belongTo_ja": "ブライト"
	},
	{
		"id": 96,
		"image_file": "iconPerks_Hoarder.png",
		"name_en": "Hoarder",
		"name_ja": "溜め込み屋",
		"name_it": "Incettatore",
		"detail_name": "Hoarder",
		"side": "killer",
		"belongTo_en": "Twins",
		"belongTo_it": "Gemelli",
		"belongTo_ja": "ツインズ"
	},
	{
		"id": 97,
		"image_file": "iconPerks_hope.png",
		"name_en": "Hope",
		"name_ja": "希望",
		"name_it": "Speranza",
		"detail_name": "hope",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 98,
		"image_file": "iconPerks_HuntressLullaby.png",
		"name_en": "Hex: Huntress Lullaby",
		"name_ja": "女狩人の子守歌",
		"name_it": "Maledizione: La ninna nanna della Cacciatrice",
		"detail_name": "huntressLullaby",
		"side": "killer",
		"belongTo_en": "Huntress",
		"belongTo_it": "Cacciatrice",
		"belongTo_ja": "ハントレス"
	},
	{
		"id": 99,
		"image_file": "iconPerks_Hyperfocus.png",
		"name_en": "Hyperfocus",
		"name_ja": "全集中",
		"name_it": "Iperconcentrazione",
		"detail_name": "hyperfocus",
		"side": "surv",
		"belongTo_en": "Rebecca Chambers",
		"belongTo_it": "Rebecca Chambers",
		"belongTo_ja": "レベッカ・チェンバース"
	},
	{
		"id": 100,
		"image_file": "iconPerks_hysteria.png",
		"name_en": "Hysteria",
		"name_ja": "集団ヒステリー",
		"name_it": "Isteria",
		"detail_name": "hysteria",
		"side": "killer",
		"belongTo_en": "Nemesis",
		"belongTo_it": "Nemesis",
		"belongTo_ja": "ネメシス"
	},
	{
		"id": 101,
		"image_file": "iconPerks_imAllEars.png",
		"name_en": "I'm All Ears",
		"name_ja": "地獄耳",
		"name_it": "Sono Tutt'Orecchi",
		"detail_name": "imAllEars",
		"side": "killer",
		"belongTo_en": "Ghost Face",
		"belongTo_it": "Ghost Face",
		"belongTo_ja": "ゴーストフェイス"
	},
	{
		"id": 102,
		"image_file": "iconPerks_infectiousFright.png",
		"name_en": "Infectious Fright",
		"name_ja": "伝播する怖気",
		"name_it": "Terrore Contagioso",
		"detail_name": "infectiousFright",
		"side": "killer",
		"belongTo_en": "Plague",
		"belongTo_it": "Malattia",
		"belongTo_ja": "プレイグ"
	},
	{
		"id": 103,
		"image_file": "iconPerks_InnerFocus.png",
		"name_en": "Inner Focus",
		"name_ja": "インナーフォーカス",
		"name_it": "Concentrazione Interiore",
		"detail_name": "innerFocus",
		"side": "surv",
		"belongTo_en": "Haddie Kaur",
		"belongTo_it": "Haddie Kaur",
		"belongTo_ja": "ハディ・カウル"
	},
	{
		"id": 104,
		"image_file": "iconPerks_survivalInstincts.png",
		// "image_file": "iconPerks_innerStrength.png",
		"name_en": "Inner Strength",
		"name_ja": "内なる力",
		"name_it": "Forza Interiore",
		"detail_name": "innerStrength",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 105,
		"image_file": "iconPerks_insidious.png",
		"name_en": "Insidious",
		"name_ja": "狡猾",
		"name_it": "Insidioso",
		"detail_name": "insidious",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 106,
		"image_file": "iconPerks_ironGrasp.png",
		"name_en": "Iron Grasp",
		"name_ja": "鋼の握力",
		"name_it": "Morsa di Ferro",
		"detail_name": "ironGrasp",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 107,
		"image_file": "iconPerks_ironMaiden.png",
		"name_en": "Iron Maiden",
		"name_ja": "アイアンメイデン",
		"name_it": "Vergine di Ferro",
		"detail_name": "ironMaiden",
		"side": "killer",
		"belongTo_en": "Legion",
		"belongTo_it": "Legione",
		"belongTo_ja": "リージョン"
	},
	{
		"id": 108,
		"image_file": "iconPerks_ironWill.png",
		"name_en": "Iron Will",
		"name_ja": "鋼の意思",
		"name_it": "Volontà di Ferro",
		"detail_name": "ironWill",
		"side": "surv",
		"belongTo_en": "Jake Park",
		"belongTo_it": "Jake Park",
		"belongTo_ja": "ジェイク・パーク"
	},
	{
		"id": 109,
		"image_file": "iconPerks_kindred.png",
		"name_en": "Kindred",
		"name_ja": "血族",
		"name_it": "Parentela",
		"detail_name": "kindred",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 110,
		"image_file": "iconPerks_knockOut.png",
		"name_en": "Knock Out",
		"name_ja": "ノックアウト",
		"name_it": "KO",
		"detail_name": "knockOut",
		"side": "killer",
		"belongTo_en": "Cannibal",
		"belongTo_it": "Cannibale",
		"belongTo_ja": "カニバル"
	},
	{
		"id": 111,
		"image_file": "iconPerks_leader.png",
		"name_en": "Leader",
		"name_ja": "リーダー",
		"name_it": "Leader",
		"detail_name": "leader",
		"side": "surv",
		"belongTo_en": "Dwight Fairfield",
		"belongTo_it": "Dwight Fairfield",
		"belongTo_ja": "ドワイト・フェアフィールド"
	},
	{
		"id": 112,
		"image_file": "iconPerks_leftBehind.png",
		"name_en": "Left Behind",
		"name_ja": "置き去りにされた者",
		"name_it": "Ultima Speranza",
		"detail_name": "leftBehind",
		"side": "surv",
		"belongTo_en": "William \"Bill\" Overbeck ",
		"belongTo_it": "William \"Bill\" Overbeck ",
		"belongTo_ja": "ウィリアム・ビル・オーバーバック"
	},
	{
		"id": 113,
		"image_file": "iconPerks_lethalPursuer.png",
		"name_en": "Lethal Pursuer",
		"name_ja": "死を呼ぶ追跡者",
		"name_it": "Inseguitore Letale",
		"detail_name": "lethalPursuer",
		"side": "killer",
		"belongTo_en": "Nemesis",
		"belongTo_it": "Nemesis",
		"belongTo_ja": "ネメシス"
	},
	{
		"id": 114,
		"image_file": "iconPerks_lightborn.png",
		"name_en": "Lightborn",
		"name_ja": "光より出でし者",
		"name_it": "Nato dalla Luce",
		"detail_name": "lightborn",
		"side": "killer",
		"belongTo_en": "Hillbilly",
		"belongTo_it": "Mandriano",
		"belongTo_ja": "ヒルビリー"
	},
	{
		"id": 115,
		"image_file": "iconPerks_lightweight.png",
		"name_en": "Light Weight",
		"name_ja": "身軽",
		"name_it": "Peso Piuma",
		"detail_name": "lightweight",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 116,
		"image_file": "iconPerks_lithe.png",
		"name_en": "Lithe",
		"name_ja": "しなやか",
		"name_it": "Agilità",
		"detail_name": "lithe",
		"side": "surv",
		"belongTo_en": "Feng Min",
		"belongTo_it": "Feng Min",
		"belongTo_ja": "フェン・ミン"
	},
	{
		"id": 117,
		"image_file": "iconPerks_LowProfile.png",
		"name_en": "Low Profile",
		"name_ja": "雲隠れ",
		"name_it": "Profilo Basso",
		"detail_name": "lowProfile",
		"side": "surv",
		"belongTo_en": "Ada Wong",
		"belongTo_it": "Ada Wong",
		"belongTo_ja": "エイダ・ウォン"
	},
	{
		"id": 118,
		"image_file": "iconPerks_luckyBreak.png",
		"name_en": "Lucky Break",
		"name_ja": "怪我の功名",
		"name_it": "Colpo di Fortuna",
		"detail_name": "luckyBreak",
		"side": "surv",
		"belongTo_en": "Yui Kimura",
		"belongTo_it": "Yui Kimura",
		"belongTo_ja": "木村 結衣"
	},
	{
		"id": 119,
		"image_file": "iconPerks_madGrit.png",
		"name_en": "Mad Grit",
		"name_ja": "狂気の根性",
		"name_it": "Tenacia Furiosa",
		"detail_name": "madGrit",
		"side": "killer",
		"belongTo_en": "Legion",
		"belongTo_it": "Legione",
		"belongTo_ja": "リージョン"
	},
	{
		"id": 120,
		"image_file": "iconPerks_makeYourChoice.png",
		"name_en": "Make Your Choice",
		"name_ja": "選択は君次第だ",
		"name_it": "Fa' la tua Scelta",
		"detail_name": "makeYourChoice",
		"side": "killer",
		"belongTo_en": "Pig",
		"belongTo_it": "Maiale",
		"belongTo_ja": "ピッグ"
	},
	{
		"id": 121,
		"image_file": "iconPerks_mercilessStorm.png",
		"name_en": "Merciless Storm",
		"name_ja": "怒涛の嵐",
		"name_it": "Tempesta Impietosa",
		"detail_name": "mercilessStorm",
		"side": "killer",
		"belongTo_en": "Onryō",
		"belongTo_it": "Onryō",
		"belongTo_ja": "怨霊"
	},
	{
		"id": 122,
		"image_file": "iconPerks_mettleOfMan.png",
		"name_en": "Mettle of Man",
		"name_ja": "英雄の奮起",
		"name_it": "Il Coraggio dell'Uomo",
		"detail_name": "mettleOfMan",
		"side": "surv",
		"belongTo_en": "Ashley J. Williams",
		"belongTo_it": "Ashley J. Williams",
		"belongTo_ja": "アシュレイ・J・ウィリアムズ"
	},
	{
		"id": 123,
		"image_file": "iconPerks_mindBreaker.png",
		"name_en": "fearmonger",
		"name_ja": "不安を煽るもの",
		"name_it": "Rompicapo",
		"detail_name": "fearmonger",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 124,
		"image_file": "iconPerks_monitorAndAbuse.png",
		"name_en": "Monitor & Abuse",
		"name_ja": "観察＆虐待",
		"name_it": "Sorveglianza e Sevizia",
		"detail_name": "",
		"side": "killer",
		"belongTo_en": "Doctor",
		"belongTo_it": "Dottore",
		"belongTo_ja": "ドクター"
	},
	{
		"id": 125,
		"image_file": "iconPerks_monstrousShrine.png",
		"name_en": "Scourge Hook: Monstrous Shrine",
		"name_ja": "異形の祭壇",
		"name_it": "Flagello Appuntito: Reliquiario Mostruoso",
		"detail_name": "",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 126,
		"image_file": "iconPerks_nemesis.png",
		"name_en": "Nemesis",
		"name_ja": "天誅",
		"name_it": "Nemesi",
		"detail_name": "nemesis",
		"side": "killer",
		"belongTo_en": "Oni",
		"belongTo_it": "Oni",
		"belongTo_ja": "鬼"
	},
	{
		"id": 127,
		"image_file": "iconPerks_NoMither.png",
		"name_en": "No Mither",
		"name_ja": "弱音はナシだ",
		"name_it": "Nessuna Bega",
		"detail_name": "noMither",
		"side": "surv",
		"belongTo_en": "David King",
		"belongTo_it": "David King",
		"belongTo_ja": "デイビット・キング"
	},
	{
		"id": 128,
		"image_file": "iconPerks_noOneEscapesDeath.png",
		"name_en": "Hex: No One Escapes Death",
		"name_ja": "誰も死から逃れられない",
		"name_it": "Maledizione: Nessuno Sfugge alla Morte",
		"detail_name": "noOneEscapesDeath",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 129,
		"image_file": "iconPerks_noOneLeftBehind.png",
		"name_en": "No one left behind",
		"name_ja": "誰も見捨てはしない",
		"name_it": "Non si Abbandona Nessuno",
		"detail_name": "noOneLeftBehind",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 130,
		"image_file": "iconPerks_NoWayOut.png",
		"name_en": "No Way Out",
		"name_ja": "袋小路",
		"name_it": "Nessuna Via d'Uscita",
		"detail_name": "NoWayOut",
		"side": "killer",
		"belongTo_en": "Trickster",
		"belongTo_it": "Ingannatore",
		"belongTo_ja": "トリックスター"
	},
	{
		"id": 131,
		"image_file": "iconPerks_objectOfObsession.png",
		"name_en": "Object of Obsession",
		"name_ja": "執念の対象",
		"name_it": "Oggetto dell'Ossessione",
		"detail_name": "objectOfObsession",
		"side": "surv",
		"belongTo_en": "Laurie Strode",
		"belongTo_it": "Laurie Strode",
		"belongTo_ja": "ローリー・ストロード"
	},
	{
		"id": 132,
		"image_file": "iconPerks_offTheRecord.png",
		"name_en": "Off the Record",
		"name_ja": "オフレコ",
		"name_it": "In Via Ufficiosa",
		"detail_name": "offTheRecord",
		"side": "surv",
		"belongTo_en": "Zarina Kassir",
		"belongTo_it": "Zarina Kassir",
		"belongTo_ja": "ザリーナ・カッシル"
	},
	{
		"id": 133,
		"image_file": "iconPerks_openHanded.png",
		"name_en": "Open-Handed",
		"name_ja": "手札公開",
		"name_it": "Carte Scoperte",
		"detail_name": "openHanded",
		"side": "surv",
		"belongTo_en": "Ace Visconti",
		"belongTo_it": "Ace Visconti",
		"belongTo_ja": "エース・ヴィスコンティ"
	},
	{
		"id": 134,
		"image_file": "iconPerks_Oppression.png",
		"name_en": "Oppression",
		"name_ja": "迫害",
		"name_it": "Oppressione",
		"detail_name": "oppression",
		"side": "killer",
		"belongTo_en": "Twins",
		"belongTo_it": "Gemelli",
		"belongTo_ja": "ツインズ"
	},
	{
		"id": 135,
		"image_file": "iconPerks_overwhelmingPresence.png",
		"name_en": "Overwhelming Presence",
		"name_ja": "圧倒的存在感",
		"name_it": "Presenza Sovrastante",
		"detail_name": "overwhelmingPresence",
		"side": "killer",
		"belongTo_en": "Doctor",
		"belongTo_it": "Dottore",
		"belongTo_ja": "ドクター"
	},
	{
		"id": 136,
		"image_file": "iconPerks_Overzealous.png",
		"name_en": "Overzealous",
		"name_ja": "過剰な熱意",
		"name_it": "Zelo Eccessivo",
		"detail_name": "overzealous",
		"side": "surv",
		"belongTo_en": "Haddie Kaur",
		"belongTo_it": "Haddie Kaur",
		"belongTo_ja": "ハディ・カウル"
	},
	{
		"id": 137,
		"image_file": "iconPerks_parentalGuidance.png",
		"name_en": "Parental Guidance",
		"name_ja": "父の助言",
		"name_it": "Guida Paterna",
		"detail_name": "parentalGuidance",
		"side": "surv",
		"belongTo_en": "Yoichi Asakawa",
		"belongTo_it": "Yoichi Asakawa",
		"belongTo_ja": "浅川陽一"
	},
	{
		"id": 138,
		"image_file": "iconPerks_pharmacy.png",
		"name_en": "Pharmacy",
		"name_ja": "調剤学",
		"name_it": "Farmacia",
		"detail_name": "pharmacy",
		"side": "surv",
		"belongTo_en": "Quentin Smith",
		"belongTo_it": "Quentin Smith",
		"belongTo_ja": "クエンティン・スミス"
	},
	{
		"id": 139,
		"image_file": "iconPerks_playWithYourFood.png",
		"name_en": "Play with Your Food",
		"name_ja": "弄ばれる獲物",
		"name_it": "Gioca con il tuo Cibo",
		"detail_name": "playWithYourFood",
		"side": "killer",
		"belongTo_en": "Shape",
		"belongTo_it": "Ombra",
		"belongTo_ja": "シェイプ"
	},
	{
		"id": 140,
		"image_file": "iconPerks_plunderersInstinct.png",
		"name_en": "Plunderer's Instinct",
		"name_ja": "コソ泥の本能",
		"name_it": "Istinto del Predatore",
		"detail_name": "plunderersInstinct",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 141,
		"image_file": "iconPerks_poised.png",
		"name_en": "Poised",
		"name_ja": "平常心",
		"name_it": "Compostezza",
		"detail_name": "poised",
		"side": "surv",
		"belongTo_en": "Jane Romero",
		"belongTo_it": "Jane Romero",
		"belongTo_ja": "ジェーン・ロメロ"
	},
	{
		"id": 142,
		"image_file": "iconPerks_popGoesTheWeasel.png",
		"name_en": "Pop Goes the Weasel",
		"name_ja": "イタチが飛び出した",
		"name_it": "Anghingò",
		"detail_name": "popGoesTheWeasel",
		"side": "killer",
		"belongTo_en": "Clown",
		"belongTo_it": "Clown",
		"belongTo_ja": "クラウン"
	},
	{
		"id": 143,
		"image_file": "iconPerks_powerStruggle.png",
		"name_en": "Power Struggle",
		"name_ja": "勢力争い",
		"name_it": "Lotta di Potere",
		"detail_name": "powerStruggle",
		"side": "surv",
		"belongTo_en": "Élodie Rakoto",
		"belongTo_it": "Élodie Rakoto",
		"belongTo_ja": "エロディー・ラコト"
	},
	{
		"id": 144,
		"image_file": "iconPerks_predator.png",
		"name_en": "Predator",
		"name_ja": "捕食者",
		"name_it": "Predatore",
		"detail_name": "predator",
		"side": "killer",
		"belongTo_en": "Wraith",
		"belongTo_it": "Spettro",
		"belongTo_ja": "レイス"
	},
	{
		"id": 145,
		"image_file": "iconPerks_premonition.png",
		"name_en": "Premonition",
		"name_ja": "予感",
		"name_it": "Premonizione",
		"detail_name": "premonition",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 146,
		"image_file": "iconPerks_proveThyself.png",
		"name_en": "Prove Thyself",
		"name_ja": "有能の証明",
		"name_it": "Mettiti alla Prova",
		"detail_name": "proveThyself",
		"side": "surv",
		"belongTo_en": "Dwight Fairfield",
		"belongTo_it": "Dwight Fairfield",
		"belongTo_ja": "ドワイト・フェアフィールド"
	},
	{
		"id": 148,
		"image_file": "iconPerks_quickAndQuiet.png",
		"name_en": "Quick & Quiet",
		"name_ja": "素早く静かに",
		"name_it": "Veloce e Silenzioso",
		"detail_name": "quickAndQuiet",
		"side": "surv",
		"belongTo_en": "Meg Thomas",
		"belongTo_it": "Meg Thomas",
		"belongTo_ja": "メグ・トーマス"
	},
	{
		"id": 149,
		"image_file": "iconPerks_ReactiveHealing.png",
		"name_en": "Reactive Healing",
		"name_ja": "反射回復",
		"name_it": "Cura Reattiva",
		"detail_name": "reactiveHealing",
		"side": "surv",
		"belongTo_en": "Ada Wong",
		"belongTo_it": "Ada Wong",
		"belongTo_ja": "エイダ・ウォン"
	},
	{
		"id": 150,
		"image_file": "iconPerks_Reassurance.png",
		"name_en": "Reassurance",
		"name_ja": "安心感",
		"name_it": "Rassicurazione",
		"detail_name": "reassurance",
		"side": "surv",
		"belongTo_en": "Rebecca Chambers",
		"belongTo_it": "Rebecca Chambers",
		"belongTo_ja": "レベッカ・チェンバース"
	},
	{
		"id": 151,
		"image_file": "iconPerks_redHerring.png",
		"name_en": "Red Herring",
		"name_ja": "おとり",
		"name_it": "Depistaggio",
		"detail_name": "redHerring",
		"side": "surv",
		"belongTo_en": "Zarina Kassir",
		"belongTo_it": "Zarina Kassir",
		"belongTo_ja": "ザリーナ・カッシル"
	},
	{
		"id": 152,
		"image_file": "iconPerks_rememberMe.png",
		"name_en": "Remember Me",
		"name_ja": "リメンバー・ミー",
		"name_it": "Ricordati di Me",
		"detail_name": "rememberMe",
		"side": "killer",
		"belongTo_en": "Nightmare",
		"belongTo_it": "Incubo",
		"belongTo_ja": "ナイトメア"
	},
	{
		"id": 153,
		"image_file": "iconPerks_repressedAlliance.png",
		"name_en": "Repressed Alliance",
		"name_ja": "抑圧の同盟",
		"name_it": "Alleanza Repressa",
		"detail_name": "repressedAlliance",
		"side": "surv",
		"belongTo_en": "Cheryl Mason",
		"belongTo_it": "Cheryl Mason",
		"belongTo_ja": "シェリル・メイソン"
	},
	{
		"id": 154,
		"image_file": "iconPerks_ResidualManifest.png",
		"name_en": "Residual Manifest",
		"name_ja": "残像の顕現",
		"name_it": "Manifesto Residuo",
		"detail_name": "residualManifest",
		"side": "surv",
		"belongTo_en": "Haddie Kaur",
		"belongTo_it": "Haddie Kaur",
		"belongTo_ja": "ハディ・カウル"
	},
	{
		"id": 155,
		"image_file": "iconPerks_resilience.png",
		"name_en": "Resilience",
		"name_ja": "逆境魂",
		"name_it": "Determinazione",
		"detail_name": "resilience",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 156,
		"image_file": "iconPerks_Resurgence.png",
		"name_en": "Resurgence",
		"name_ja": "起死回生",
		"name_it": "Reviviscenza",
		"detail_name": "",
		"side": "surv",
		"belongTo_it": "Jill Valentine",
		"belongTo_en": "Jill Valentine",
		"belongTo_ja": "ジル・バレンタイン"
	},
	{
		"id": 157,
		"image_file": "iconPerks_RookieSpirit.png",
		"name_en": "Rookie Spirit",
		"name_ja": "新人魂",
		"name_it": "Recluta",
		"detail_name": "rookieSpirit",
		"side": "surv",
		"belongTo_en": "Leon Scott Kennedy",
		"belongTo_it": "Leon Scott Kennedy",
		"belongTo_ja": "レオン・S・ケネディ"
	},
	{
		"id": 158,
		"image_file": "iconPerks_ruin.png",
		"name_en": "Hex: Ruin",
		"name_ja": "破滅",
		"name_it": "Maledizione: Rovina",
		"detail_name": "ruin",
		"side": "killer",
		"belongTo_en": "Hag",
		"belongTo_it": "Strega",
		"belongTo_ja": "ハグ"
	},
	{
		"id": 159,
		"image_file": "iconPerks_saboteur.png",
		"name_en": "Saboteur",
		"name_ja": "サボタージュ",
		"name_it": "Sabotatore",
		"detail_name": "saboteur",
		"side": "surv",
		"belongTo_en": "Jake Park",
		"belongTo_it": "Jake Park",
		"belongTo_ja": "ジェイク・パーク"
	},
	{
		"id": 160,
		"image_file": "iconPerks_saveTheBestForLast.png",
		"name_en": "Save the Best for Last",
		"name_ja": "最後のお楽しみ",
		"name_it": "Conserva il Meglio per la Fine",
		"detail_name": "saveTheBestForLast",
		"side": "killer",
		"belongTo_en": "Shape",
		"belongTo_it": "Ombra",
		"belongTo_ja": "シェイプ"
	},
	{
		"id": 161,
		"image_file": "iconPerks_ScourgeHookGiftOfPain.png",
		"name_en": "Scourge Hook: Gift of Pain",
		"name_ja": "悶絶：苦痛という名の賜り物",
		"name_it": "Flagello Appuntito: Dono del Dolore",
		"detail_name": "",
		"side": "killer",
		"belongTo_en": "Cenobite",
		"belongTo_it": "Cenobita",
		"belongTo_ja": "セノバイト"
	},
	{
		"id": 162,
		"image_file": "iconPerks_secondWind.png",
		"name_en": "Second Wind",
		"name_ja": "セカンドウインド",
		"name_it": "Nuova Energia",
		"detail_name": "secondWind",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 163,
		"image_file": "iconPerks_selfCare.png",
		"name_en": "Self-Care",
		"name_ja": "セルフケア",
		"name_it": "Cura di Sé",
		"detail_name": "selfCare",
		"side": "surv",
		"belongTo_en": "Claudette Morel",
		"belongTo_it": "Claudette Morel",
		"belongTo_ja": "クローデット・モレル"
	},
	{
		"id": 164,
		"image_file": "iconPerks_Self-Preservation.png",
		"name_en": "Self-Preservation",
		"name_ja": "自己防衛",
		"name_it": "Autoprotezione",
		"detail_name": "selfPreservation",
		"side": "surv",
		"belongTo_en": "Yun-Jin Lee",
		"belongTo_it": "Yun-Jin Lee",
		"belongTo_ja": "リー・ユンジン"
	},
	{
		"id": 165,
		"image_file": "iconPerks_SepticTouch.png",
		"name_en": "Septic Touch",
		"name_ja": "腐敗の気配",
		"name_it": "Tocco Settico",
		"detail_name": "septicTouch",
		"side": "killer",
		"belongTo_en": "Dredge",
		"belongTo_it": "Draga",
		"belongTo_ja": "ドレッジ"
	},
	{
		"id": 166,
		"image_file": "iconPerks_shadowborn.png",
		"name_en": "Shadowborn",
		"name_ja": "闇より出でし者",
		"name_it": "Nato dalle Tenebre",
		"detail_name": "shadowborn",
		"side": "killer",
		"belongTo_en": "Wraith",
		"belongTo_it": "Spettro",
		"belongTo_ja": "レイス"
	},
	{
		"id": 167,
		"image_file": "iconPerks_situationalAwareness.png",
		"name_en": "Situational Awareness",
		"name_ja": "一緒にいよう",
		"name_it": "Percezione Circostanziale",
		"detail_name": "situationalAwareness",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 168,
		"image_file": "iconPerks_slipperyMeat.png",
		"name_en": "Slippery Meat",
		"name_ja": "ツルツルとした肉体",
		"name_it": "Carne Sfuggente",
		"detail_name": "slipperyMeat",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 169,
		"image_file": "iconPerks_sloppyButcher.png",
		"name_en": "Sloppy Butcher",
		"name_ja": "ずさんな肉屋",
		"name_it": "Macellaio Approssimativo",
		"detail_name": "sloppyButcher",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 170,
		"image_file": "iconPerks_smallGame.png",
		"name_en": "Small Game",
		"name_ja": "小さな獲物",
		"name_it": "Piccole Prede",
		"detail_name": "smallGame",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 171,
		"image_file": "iconPerks_SmashHit.png",
		"name_en": "Smash Hit",
		"name_ja": "大ヒット",
		"name_it": "Hit di Successo",
		"detail_name": "smashHit",
		"side": "surv",
		"belongTo_en": "Yun-Jin Lee",
		"belongTo_it": "Yun-Jin Lee",
		"belongTo_ja": "リー・ユンジン"
	},
	{
		"id": 172,
		"image_file": "iconPerks_soleSurvivor.png",
		"name_en": "Sole Survivor",
		"name_ja": "唯一の生存者",
		"name_it": "Unico Sopravvissuto",
		"detail_name": "soleSurvivor",
		"side": "surv",
		"belongTo_en": "Laurie Strode",
		"belongTo_it": "Laurie Strode",
		"belongTo_ja": "ローリー・ストロード"
	},
	{
		"id": 173,
		"image_file": "iconPerks_solidarity.png",
		"name_en": "Solidarity",
		"name_ja": "連帯感",
		"name_it": "Solidarietà",
		"detail_name": "solidarity",
		"side": "surv",
		"belongTo_en": "Jane Romero",
		"belongTo_it": "Jane Romero",
		"belongTo_ja": "ジェーン・ロメロ"
	},
	{
		"id": 174,
		"image_file": "iconPerks_soulGuard.png",
		"name_en": "Soul Guard",
		"name_ja": "ソウルガード",
		"name_it": "Guardia Spirituale",
		"detail_name": "soulGuard",
		"side": "surv",
		"belongTo_en": "Cheryl Mason",
		"belongTo_it": "Cheryl Mason",
		"belongTo_ja": "シェリル・メイソン"
	},
	{
		"id": 175,
		"image_file": "iconPerks_spiesFromTheShadows.png",
		"name_en": "Spies from the Shadows",
		"name_ja": "影の密偵",
		"name_it": "Spie dalle Ombre",
		"detail_name": "spiesFromTheShadows",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 176,
		"image_file": "iconPerks_spineChill.png",
		"name_en": "Spine Chill",
		"name_ja": "凍りつく背筋",
		"name_it": "Brivido di Paura",
		"detail_name": "spineChill",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 177,
		"image_file": "iconPerks_spiritFury.png",
		"name_en": "Spirit Fury",
		"name_ja": "怨霊の怒り",
		"name_it": "Furia dello Spirito",
		"detail_name": "spiritFury",
		"side": "killer",
		"belongTo_en": "Spirit",
		"belongTo_it": "Spirito",
		"belongTo_ja": "スピリット"
	},
	{
		"id": 178,
		"image_file": "iconPerks_sprintBurst.png",
		"name_en": "Sprint Burst",
		"name_ja": "全力疾走",
		"name_it": "Scatto Improvviso",
		"detail_name": "sprintBurst",
		"side": "surv",
		"belongTo_en": "Meg Thomas",
		"belongTo_it": "Meg Thomas",
		"belongTo_ja": "メグ・トーマス"
	},
	{
		"id": 179,
		"image_file": "iconPerks_stakeOut.png",
		"name_en": "Stake Out",
		"name_ja": "張り込み",
		"name_it": "Sotto Controllo",
		"detail_name": "stakeOut",
		"side": "surv",
		"belongTo_en": "Detective David Tapp",
		"belongTo_it": "Detective David Tapp",
		"belongTo_ja": "タップ刑事"
	},
	{
		"id": 180,
		"image_file": "iconPerks_Starstruck.png",
		"name_en": "Starstruck",
		"name_ja": "スターに憧れて",
		"name_it": "Fame di Fama",
		"detail_name": "starstruck",
		"side": "killer",
		"belongTo_en": "Trickster",
		"belongTo_it": "Ingannatore",
		"belongTo_ja": "トリックスター"
	},
	{
		"id": 181,
		"image_file": "iconPerks_streetwise.png",
		"name_en": "Streetwise",
		"name_ja": "都会の生存術",
		"name_it": "Saper Stare al Mondo",
		"detail_name": "streetwise",
		"side": "surv",
		"belongTo_en": "Nea Karlsson",
		"belongTo_it": "Nea Karlsson",
		"belongTo_ja": "ネア・カールソン"
	},
	{
		"id": 182,
		"image_file": "iconPerks_stridor.png",
		"name_en": "Stridor",
		"name_ja": "喘鳴",
		"name_it": "Stridore",
		"detail_name": "stridor",
		"side": "killer",
		"belongTo_en": "Nurse",
		"belongTo_it": "Infermiera",
		"belongTo_ja": "ナース"
	},
	{
		"id": 183,
		"image_file": "iconPerks_SuperiorAnatomy.png",
		"name_en": "Superior Anatomy",
		"name_ja": "人体の超越",
		"name_it": "Anatomia Superiore",
		"detail_name": "superiorAnatomy",
		"side": "killer",
		"belongTo_en": "Mastermind",
		"belongTo_it": "Mastermind",
		"belongTo_ja": "マスターマインド"
	},
	{
		"id": 184,
		"image_file": "iconPerks_surge.png",
		"name_en": "Jolt",
		"name_ja": "景気づけ",
		"name_it": "Scossa",
		"detail_name": "jolt",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 185,
		"image_file": "iconPerks_surveillance.png",
		"name_en": "Surveillance",
		"name_ja": "監視",
		"name_it": "Sorveglianza",
		"detail_name": "surveillance",
		"side": "killer",
		"belongTo_en": "Pig",
		"belongTo_it": "Maiale",
		"belongTo_ja": "ピッグ"
	},
	{
		"id": 187,
		"image_file": "iconPerks_technician.png",
		"name_en": "Technician",
		"name_ja": "テクニシャン",
		"name_it": "Tecnico",
		"detail_name": "technician",
		"side": "surv",
		"belongTo_en": "Feng Min",
		"belongTo_it": "Feng Min",
		"belongTo_ja": "フェン・ミン"
	},
	{
		"id": 188,
		"image_file": "iconPerks_tenacity.png",
		"name_en": "Tenacity",
		"name_ja": "執念",
		"name_it": "Tenacia",
		"detail_name": "tenacity",
		"side": "surv",
		"belongTo_en": "Detective David Tapp",
		"belongTo_it": "Detective David Tapp",
		"belongTo_ja": "タップ刑事"
	},
	{
		"id": 189,
		"image_file": "iconPerks_Terminus.png",
		"name_en": "Terminus",
		"name_ja": "終末期",
		"name_it": "Capolinea",
		"detail_name": "terminus",
		"side": "killer",
		"belongTo_en": "Mastermind",
		"belongTo_it": "Mastermind",
		"belongTo_ja": "マスターマインド"
	},
	{
		"id": 190,
		"image_file": "iconPerks_TerritorialImperative.png",
		"name_en": "Territorial Imperative",
		"name_ja": "縄張り意識",
		"name_it": "Dominio Territoriale",
		"detail_name": "territorialImperative",
		"side": "killer",
		"belongTo_en": "Huntress",
		"belongTo_it": "Cacciatrice",
		"belongTo_ja": "ハントレス"
	},
	{
		"id": 191,
		"image_file": "iconPerks_thatanophobia.png",
		"name_en": "Thanatophobia",
		"name_ja": "死恐怖症",
		"name_it": "Tanatofobia",
		"detail_name": "thatanophobia",
		"side": "killer",
		"belongTo_en": "Nurse",
		"belongTo_it": "Infermiera",
		"belongTo_ja": "ナース"
	},
	{
		"id": 192,
		"image_file": "iconPerks_theThirdSeal.png",
		"name_en": "Hex: The Third Seal",
		"name_ja": "第三の封印",
		"name_it": "Maledizione: Il Terzo Sigillo",
		"detail_name": "",
		"side": "killer",
		"belongTo_en": "Hag",
		"belongTo_it": "Strega",
		"belongTo_ja": "ハグ"
	},
	{
		"id": 193,
		"image_file": "iconPerks_thisIsNotHappening.png",
		"name_en": "This Is Not Happening",
		"name_ja": "痛みも気から",
		"name_it": "Dimmi che non sta accadendo per davvero",
		"detail_name": "thisIsNotHappening",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 194,
		"image_file": "iconPerks_thrillingTremors.png",
		"name_en": "Thrilling Tremors",
		"name_ja": "Tremori Frementi",
		"name_it": "戦慄",
		"detail_name": "thrillingTremors",
		"side": "killer",
		"belongTo_en": "Ghost Face",
		"belongTo_it": "Ghost Face",
		"belongTo_ja": "ゴーストフェイス"
	},
	{
		"id": 195,
		"image_file": "iconPerks_thrillOfTheHunt.png",
		"name_en": "Hex: Thrill of the Hunt",
		"name_ja": "狩りの興奮",
		"name_it": "Maledizione: Il Brivido della Caccia",
		"detail_name": "thrillOfTheHunt",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 196,
		"image_file": "iconPerks_tinkerer.png",
		"name_en": "Tinkerer",
		"name_ja": "ガラクタいじり",
		"name_it": "Mastro Ferraio",
		"detail_name": "tinkerer",
		"side": "killer",
		"belongTo_en": "Hillbilly",
		"belongTo_it": "Mandriano",
		"belongTo_ja": "ヒルビリー"
	},
	{
		"id": 197,
		"image_file": "iconPerks_trailOfTorment.png",
		"name_en": "Trail of Torment",
		"name_ja": "煩悶のトレイル",
		"name_it": "Scia del Tormento",
		"detail_name": "trailOfTorment",
		"side": "killer",
		"belongTo_en": "Executioner",
		"belongTo_it": "Boia",
		"belongTo_ja": "エクセキューショナー"
	},
	{
		"id": 198,
		"image_file": "iconPerks_unbreakable.png",
		"name_en": "Unbreakable",
		"name_ja": "不滅",
		"name_it": "Volontà d'Acciaio",
		"detail_name": "unbreakable",
		"side": "surv",
		"belongTo_en": "William \"Bill\" Overbeck ",
		"belongTo_it": "William \"Bill\" Overbeck ",
		"belongTo_ja": "ウィリアム・ビル・オーバーバック"
	},
	{
		"id": 199,
		"image_file": "iconPerks_unnervingPresence.png",
		"name_en": "Unnerving Presence",
		"name_ja": "不安の元凶",
		"name_it": "Presenza Inquietante",
		"detail_name": "unnervingPresence",
		"side": "killer",
		"belongTo_en": "Trapper",
		"belongTo_it": "Cacciatore",
		"belongTo_ja": "トラッパー"
	},
	{
		"id": 200,
		"image_file": "iconPerks_unrelenting.png",
		"name_en": "Unrelenting",
		"name_ja": "無慈悲",
		"name_it": "Inarrestabile",
		"detail_name": "unrelenting",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 201,
		"image_file": "iconPerks_upTheAnte.png",
		"name_en": "Up the Ante",
		"name_ja": "賭け金のレイズ",
		"name_it": "Alza la Posta",
		"detail_name": "upTheAnte",
		"side": "surv",
		"belongTo_en": "Ace Visconti",
		"belongTo_it": "Ace Visconti",
		"belongTo_ja": "エース・ヴィスコンティ"
	},
	{
		"id": 202,
		"image_file": "iconPerks_urbanEvasion.png",
		"name_en": "Urban Evasion",
		"name_ja": "都会の逃走術",
		"name_it": "Evasione Urbana",
		"detail_name": "urbanEvasion",
		"side": "surv",
		"belongTo_en": "Nea Karlsson",
		"belongTo_it": "Nea Karlsson",
		"belongTo_ja": "ネア・カールソン"
	},
	{
		"id": 203,
		"image_file": "iconPerks_vigil.png",
		"name_en": "Vigil",
		"name_ja": "寝ずの番",
		"name_it": "Veglia",
		"detail_name": "vigil",
		"side": "surv",
		"belongTo_en": "Quentin Smith",
		"belongTo_it": "Quentin Smith",
		"belongTo_ja": "クエンティン・スミス"
	},
	{
		"id": 204,
		"image_file": "iconPerks_visionary.png",
		"name_en": "Visionary",
		"name_ja": "透視家",
		"name_it": "Visionario",
		"detail_name": "visionary",
		"side": "surv",
		"belongTo_en": "Felix Richter",
		"belongTo_it": "Felix Richter",
		"belongTo_ja": "フェリックス・リクター"
	},
	{
		"id": 205,
		"image_file": "iconPerks_wakeUp.png",
		"name_en": "Wake Up!",
		"name_ja": "目を覚ませ！",
		"name_it": "Sveglia!",
		"detail_name": "wakeUp",
		"side": "surv",
		"belongTo_en": "Quentin Smith",
		"belongTo_it": "Quentin Smith",
		"belongTo_ja": "クエンティン・スミス"
	},
	{
		"id": 206,
		"image_file": "iconPerks_wellMakeIt.png",
		"name_en": "We'll Make It",
		"name_ja": "きっとやり遂げる",
		"name_it": "Ce La Faremo",
		"detail_name": "wellMakeIt",
		"side": "surv",
		"belongTo_en": "Survivor General",
		"belongTo_it": "Generale Sopravvissuto",
		"belongTo_ja": "サバイバー共通"
	},
	{
		"id": 207,
		"image_file": "iconPerks_WereGonnaLiveForever.png",
		"name_en": "We're Gonna Live Forever",
		"name_ja": "ずっと一緒だ",
		"name_it": "Vivremo per Sempre",
		"detail_name": "wereGonnaLiveForever",
		"side": "surv",
		"belongTo_en": "David King",
		"belongTo_it": "David King",
		"belongTo_ja": "デイビット・キング"
	},
	{
		"id": 208,
		"image_file": "iconPerks_whispers.png",
		"name_en": "Whispers",
		"name_ja": "囁き",
		"name_it": "Sussurri",
		"detail_name": "whispers",
		"side": "killer",
		"belongTo_en": "Killer General",
		"belongTo_it": "Generale Assassino",
		"belongTo_ja": "キラー共通"
	},
	{
		"id": 209,
		"image_file": "iconPerks_windowsOfOpportunity.png",
		"name_en": "Windows of Opportunity",
		"name_ja": "好機の窓",
		"name_it": "Momenti Propizi",
		"detail_name": "windowsOfOpportunity",
		"side": "surv",
		"belongTo_en": "Kate Denson",
		"belongTo_it": "Kate Denson",
		"belongTo_ja": "ケイト・デンソン"
	},
	{
		"id": 210,
		"image_file": "iconPerks_Wiretap.png",
		"name_en": "Wiretap",
		"name_ja": "盗聴",
		"name_it": "Microspia",
		"detail_name": "wiretap",
		"side": "surv",
		"belongTo_en": "Ada Wong",
		"belongTo_it": "Ada Wong",
		"belongTo_ja": "エイダ・ウォン"
	},
	{
		"id": 211,
		"image_file": "iconPerks_zanshinTactics.png",
		"name_en": "Zanshin Tactics",
		"name_ja": "残心の戦術",
		"name_it": "Tattica Zanshin",
		"detail_name": "zanshinTactics",
		"side": "killer",
		"belongTo_en": "Oni",
		"belongTo_it": "Oni",
		"belongTo_ja": "鬼"
	},
	{
		"id": 212,
		"image_file": "T_iconPerks_BoonExponential.png",
		"name_en": "Boon: Exponential",
		"name_ja": "恵み：指数関数",
		"name_it": "Manna: Esponenziale",
		"detail_name": "boonExponential",
		"side": "surv",
		"belongTo_en": "Jonah Vasquez",
		"belongTo_it": "Jonah Vasquez",
		"belongTo_ja": "ジョナ・バスキス"
	},
	{
		"id": 213,
		"image_file": "T_iconPerks_CorrectiveAction.png",
		"name_en": "Corrective Action",
		"name_ja": "是正措置",
		"name_it": "Azione Correttiva",
		"detail_name": "correctiveAction",
		"side": "surv",
		"belongTo_en": "Jonah Vasquez",
		"belongTo_it": "Jonah Vasquez",
		"belongTo_ja": "ジョナ・バスキス"
	},
	{
		"id": 214,
		"image_file": "T_iconPerks_grimEmbrace.png",
		"name_en": "Grim Embrace",
		"name_ja": "不吉な包囲",
		"name_it": "Abbraccio Lugubre",
		"detail_name": "grimEmbrace",
		"side": "killer",
		"belongTo_en": "Artist",
		"belongTo_it": "Artista",
		"belongTo_ja": "アーティスト"
	},
	{
		"id": 215,
		"image_file": "T_iconPerks_hexPentimento.png",
		"name_en": "Hex: Pentimento",
		"name_ja": "ペンティメント",
		"name_it": "Maledizione: Pentimento",
		"detail_name": "hexPentimento",
		"side": "killer",
		"belongTo_en": "Artist",
		"belongTo_it": "Artista",
		"belongTo_ja": "アーティスト"
	},
	{
		"id": 216,
		"image_file": "T_iconPerks_Overcome.png",
		"name_en": "Overcome",
		"name_ja": "打開策",
		"name_it": "Risoluzione",
		"detail_name": "overcome",
		"side": "surv",
		"belongTo_en": "Jonah Vasquez",
		"belongTo_it": "Jonah Vasquez",
		"belongTo_ja": "ジョナ・バスキス"
	},
	{
		"id": 217,
		"image_file": "T_iconPerks_painResonance.png",
		"name_en": "Scourge Hook: Pain Resonance",
		"name_ja": "悶絶：共鳴する苦痛",
		"name_it": "Flagello Appuntito: Eco di Dolore",
		"detail_name": "painResonance",
		"side": "killer",
		"belongTo_en": "Artist",
		"belongTo_it": "Artista",
		"belongTo_ja": "アーティスト"
	},
	{
		"id": 218,
		"image_file": "iconPerks_NowhereToHide.png",
		"name_en": "Nowhere to Hide",
		"name_ja": "隠れ場なし",
		"name_it": "Impossibile Nascondersi",
		"detail_name": "NowhereToHide",
		"side": "killer",
		"belongTo_en": "Knight",
		"belongTo_it": "Cavaliere",
		"belongTo_ja": "ナイト"
	},
	{
		"id": 219,
		"image_file": "iconPerks_HexFaceTheDarkness.png",
		"name_en": "Hex: Face the Darkness",
		"name_ja": "闇との対面",
		"name_it": "Maledizione: Affronta l'Oscurità",
		"detail_name": "HexFaceTheDarkness",
		"side": "killer",
		"belongTo_en": "Knight",
		"belongTo_it": "Cavaliere",
		"belongTo_ja": "ナイト"
	},
	{
		"id": 220,
		"image_file": "iconPerks_Hubris.png",
		"name_en": "Hubris",
		"name_ja": "ヒュブリス",
		"name_it": "Boria",
		"detail_name": "HexFaceTheDarkness",
		"side": "killer",
		"belongTo_en": "Knight",
		"belongTo_it": "Cavaliere",
		"belongTo_ja": "ナイト"
	},
	{
		"id": 221,
		"image_file": "iconPerks_PotentialEnergy.png",
		"name_en": "Potential Energy",
		"name_ja": "位置エネルギー",
		"name_it": "Energia Potenziale",
		"detail_name": "PotentialEnergy",
		"side": "surv",
		"belongTo_en": "Vittorio Toscano",
		"belongTo_it": "Vittorio Toscano",
		"belongTo_ja": "ビットリオ・トスカーノ"
	},
	{
		"id": 222,
		"image_file": "iconPerks_Fogwise.png",
		"name_en": "Fogwise",
		"name_ja": "霧の作法",
		"name_it": "Strade Nebbiose",
		"detail_name": "Fogwise",
		"side": "surv",
		"belongTo_en": "Vittorio Toscano",
		"belongTo_it": "Vittorio Toscano",
		"belongTo_ja": "ビットリオ・トスカーノ"
	},
	{
		"id": 223,
		"image_file": "iconPerks_VittoriosGambit.png",
		"name_en": "Quick Gambit",
		"name_ja": "加速の策略",
		"name_it": "Lampo di Genio",
		"detail_name": "VittoriosGambit",
		"side": "surv",
		"belongTo_en": "Vittorio Toscano",
		"belongTo_it": "Vittorio Toscano",
		"belongTo_ja": "ビットリオ・トスカーノ"
	}
];
